### PR TITLE
feat: Support navigating to code when clicking on a node

### LINKED ISSUE #2: Support navigating to code when clicking on a node

### PR DESCRIPTION
**Pull request by raul-saez**
Closes #2

### CODE REVIEW

**Review by simoneb — APPROVED** [review]
When this is ready please request a review, I'm not sure if it's ready or not, since it's not draft but it doesn't have reviewers either (and I don't remember it being posted on slack)

**Review by grantmorrison — APPROVED** [review]
LGTM.

Clicking on a node directs to the file in VSCode when the node is a project file, and its data has a source property.

**Comment by simoneb** [comment]
@Eomm are we good to go ahead with this?

**Comment by Eomm** [comment]
In the worse case, Monday I will be able to provide a complete feedback.

Feel free to merge if necessary 👍🏼

**Comment by simoneb** [comment]
@grantmorrison did this work for you? If so, please merge and switch to the other PR so we can do a release after confirming that this is working without mocked data

**Comment by grantmorrison** [comment]
Yeah this worked for me :)

Clicking on a node directs to the file in VSCode when the node is a project file, and its data has a source property.

I'll merge I now.

**Pull request merged**
